{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- if .Values.secrets.data.METRICS_TOKEN }}
      authorization:
        type: Bearer
        credentials:
          name: {{ include "app.secretName" . }}
          key: METRICS_TOKEN
      {{- end }}
{{- end }}
